### ISSUE TITLE
Remove io.js as node runtime when reporting version information

### ISSUE THREAD

**Issue by megastef** [sematext/spm-agent#10]
The agent reports wrong nodejs runtime "io.js" for node > 10.x

See: https://github.com/sematext/spm-agent/blob/master/lib/sender/influxsender.js#L167-L170

In Sematext Events view "io.js 12.14.1" should be "node 12.14.1": 
![Screen Shot 2020-02-13 at 13 03 52](https://user-images.githubusercontent.com/7289505/74434036-e2acef80-4e61-11ea-83c3-cea985a03024.png)

**Comment by otisg** [comment]
Fixed with #11
