### ISSUE TITLE
Send multiple tags instead of concatenating N tags into 1 tag

### ISSUE THREAD

**Issue by otisg** [sematext/spm-agent#2]
I think this should send an array of tags instead of sending 1 tag with N comma-separated values:

https://github.com/sematext/spm-agent/blob/5f3c5946966cf6653393693c91f134c24f5b0799/lib/sender/spmsender.js#L196

**Comment by rabbitstack** [comment]
Now when I look closer at it, `info.split` actually returns an array of strings, i.e. multiple tags. I'll have to adjust this in STA. My apologizes for creating confusion.
